<html>
    <head>
        <title>Autenticação</title>
    </head>
    <body>
        <form action="<?=HOME;?>/login" method="post">
            <p>
                <label>E-mail</label>
                <input type="email" name="email">
            </p>

            <p>
                <label>Senha</label>
                <input type="password" name="senha">
            </p>

            <button type="submit">Acessar</button>
        </form>
    </body>
</html>